# Variant Consistency Pipeline Configuration

# 1. Global VCF and donor reference data
vcf: "/u/project/cluo/terencew/igvf/pilot/multiome/vcf/pilot_000.vcf.gz"
donors: "/u/project/cluo/terencew/igvf/pilot/multiome/txt/donors.txt"

# 2. Sequencing run BAM and barcodes file
runs:
  "20220928-IGVF-D0":
    bam: "/u/project/cluo/terencew/igvf/pilot/multiome/mapping/cr_arc/igvf_ref/20220928-IGVF-D0/outs/gex_possorted_bam.bam"
    barcodes: "/u/project/cluo/terencew/igvf/pilot/multiome/mapping/cr_arc/igvf_ref/20220928-IGVF-D0/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"

# 3. Base directory for results and user-defined prefix for specific run
out_root: "var_con_output"
out_prefix: "run_v3_env-test"

# 4. Pipeline parameters (change coverage level if desired)
coverage: 0
